-- Active: 1681911512254@@127.0.0.1@3306@barasserie
CREATE TABLE PRODUCT(  
    id INT NOT NULL AUTO_INCREMENT ,
    name VARCHAR(255) NOT NULL,
    actualUnitPrice DECIMAL(4,2) NOT NULL,
    remainingQuantity INT NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE DOC_TYPE(
    code VARCHAR(32) NOT NULL,
    desciption VARCHAR(255) NOT NULL,
    PRIMARY KEY (code)
) Engine=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE DOC_STATUS(
    code VARCHAR(32) NOT NULL,
    desciption VARCHAR(255) NOT NULL,
    PRIMARY KEY (code)
) Engine=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE WORKFLOW_TYPE(
    code VARCHAR(32) NOT NULL,
    desciption VARCHAR(255) NOT NULL,
    PRIMARY KEY (code)
) Engine=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE COMMUNICATION_TYPE(
    type VARCHAR(32) NOT NULL,
    PRIMARY KEY (type)
) Engine=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE ENTITY_STATUS(
    code VARCHAR(32) NOT NULL,
    desciption VARCHAR(255) NOT NULL,
    PRIMARY KEY (code)
) Engine=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE COUNTRY(
    name VARCHAR(50) NOT NULL,
    PRIMARY KEY (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE CITY(
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(60) NOT NULL,
    postalCode INT NOT NULL,
    country VARCHAR(50) NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (country) REFERENCES COUNTRY(name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE ADDRESS(
    id INT NOT NULL AUTO_INCREMENT,
    street VARCHAR(100) NOT NULL,
    number INT NOT NULL,
    city INT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (city) REFERENCES CITY(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE BUSSINESS_ENTITY(
    id INT NOT NULL AUTO_INCREMENT,
    address INT NOT NULL,
    tier VARCHAR(32) NOT NULL,
    lastname VARCHAR(50) NOT NULL,
    firstname VARCHAR(50),
    isClient BOOLEAN NOT NULL,
    isSupplier BOOLEAN NOT NULL,
    registrationDate DATE,
    creditLimit DECIMAL(5,2),
    hashedPassword VARCHAR(255),
    salt VARCHAR(5),
    PRIMARY KEY (id),
    FOREIGN KEY (address) REFERENCES ADDRESS(id),
    Foreign Key (tier) REFERENCES ENTITY_STATUS(code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE BANKING_INFO(
    entity INT NOT NULL,
    iban VARCHAR(34) NOT NULL,
    bic VARCHAR(11),
    PRIMARY KEY (entity),
    FOREIGN KEY (entity) REFERENCES BUSSINESS_ENTITY(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE CONTACT(
    contact1 INT NOT NULL,
    contact2 INT NOT NULL,
    PRIMARY KEY (contact1, contact2),
    FOREIGN KEY (contact1) REFERENCES BUSSINESS_ENTITY(id),
    FOREIGN KEY (contact2) REFERENCES BUSSINESS_ENTITY(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE COMMUNICATION(
    entity INT NOT NULL,
    type VARCHAR(32) NOT NULL,
    communicationDetails VARCHAR(255) NOT NULL,
    PRIMARY KEY (entity, type),
    FOREIGN KEY (entity) REFERENCES BUSSINESS_ENTITY(id),
    FOREIGN KEY (type) REFERENCES COMMUNICATION_TYPE(type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE WORKFLOW(
    code VARCHAR(32) NOT NULL,
    agent INT NOT NULL,
    type VARCHAR(32) NOT NULL,
    isClosed BOOLEAN NOT NULL,
    PRIMARY KEY (code),
    FOREIGN KEY (agent) REFERENCES BUSSINESS_ENTITY(id),
    FOREIGN KEY (type) REFERENCES WORKFLOW_TYPE(code)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE DOCUMENT(
    id INT NOT NULL AUTO_INCREMENT,
    docType VARCHAR(32) NOT NULL,
    docStatus VARCHAR(32) NOT NULL,
    workflow VARCHAR(32) NOT NULL,
    date DATE NOT NULL,
    exclVATTotal DECIMAL(5,2) NOT NULL,
    inclVATTotal DECIMAL(5,2) NOT NULL,
    reminderCount INT,
    payementDeadline DATE,
    PRIMARY KEY (id,docType),
    FOREIGN KEY (docType) REFERENCES DOC_TYPE(code),
    FOREIGN KEY (docStatus) REFERENCES DOC_STATUS(code),
    FOREIGN KEY (workflow) REFERENCES WORKFLOW(code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE TRANSACTION_DETAIL(
    code VARCHAR(32) NOT NULL,
    document INT NOT NULL,
    docType VARCHAR(32) NOT NULL,
    product INT NOT NULL,
    quantity INT NOT NULL,
    unitPrice DECIMAL(4,2) NOT NULL,
    PRIMARY KEY (code, document, docType),
    FOREIGN KEY (document, docType) REFERENCES DOCUMENT(id, docType),
    FOREIGN KEY (product) REFERENCES PRODUCT(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

